name: Keep Render Webapp Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the webapp
        run: |
          curl --max-time 7 -X GET https://darija-back.onrender.com
        shell: bash
